services:
  - type: web
    name: investigador-digital
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: APP_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: REMEMBER_COOKIE_SECURE
        value: "true"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_ADMIN_USERNAME
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
